### ISSUE TITLE
look in home directory for clustery.yaml by default

### ISSUE THREAD

**Issue by cdfox-asapp** [asappresearch/flambe#104]
I was just thinking, maybe it would be convenient to have a standard location where flambe will look for the cluster.yaml, so then you wouldn't need to mention it in each flambe command.

**Comment by jeremyasapp** [comment]
Hmm I think that could be convenient but at the same time, what if you want to quickly run locally for debugging purposes? You wouldn't want it to launch on the cluster because you forgot there was a cluster file there right?

**Comment by cdfox-asapp** [comment]
how about this:

If you specify `--cluster` without providing a cluster YAML file, the flambe by default looks for a file ~/.flambe/cluster.yaml. If you do not specify `--cluster` flag at all, it's a local run.

**Comment by jeremyasapp** [comment]
That's implemented in 0.5 :)
