### ISSUE TITLE
Add a fail fast option for experiments

### ISSUE THREAD

**Issue by nmatthews-asapp** [asappresearch/flambe#105]
**Is your feature request related to a problem? Please describe.**
Currently the experiment always progresses to later stages even if there was a trial error. This is sometimes okay, but there should be some kind of opt-in feature to stop as soon as a trial fails to avoid wasted computation.

**Describe the solution you'd like**
Opt-in flag on `Experiment` that can be set in either the config or via the CLI

**Comment by iitzco-asapp** [comment]
Done in #106
