### ISSUE TITLE
An example of __init__.py in custom extensions

### ISSUE THREAD

**Issue by peterAsapp** [asappresearch/flambe#142]
**Is your feature request related to a problem? Please describe.**
I forgot to set up `__init__.py` properly in my custom extension, and the error message is not quite obvious about what went wrong.

**Describe the solution you'd like**
It'd be great to have an example of an `__init__.py` in the doc just like the one for `setup.py`.

**Describe alternatives you've considered**
Asking @nmatthews-asapp, who helped me out!

**Additional context**

**Comment by jeremyasapp** [comment]
I believe this is explained in the docs here: https://flambe.ai/en/latest/understanding/extensions.html

Either way, will be irrelevant in 0.5
