### ISSUE TITLE
AvgPooling fails even when input dimensions match expected ones.

### ISSUE THREAD

**Issue by ciguaran-asapp** [asappresearch/flambe#164]
**Describe the bug**
An error pop's up when using the forward method from AvgPooling

**To Reproduce**
Use the layer with any matching dimensions. 
 return data / padding_mask.sum(dim=1)
RuntimeError: The size of tensor a (300) must match the size of tensor b (64) at non-singleton dimension 1

**Expected behavior**
The result should be the average, given the padding_mask. 

**Software Versions (please complete the following information):**
 - Flambé Version 0.4.7

**Comment by iitzco-asapp** [comment]
Done in #165
