### ISSUE TITLE
`flambe clean` option

### ISSUE THREAD

**Issue by williamabrwolf** [asappresearch/flambe#29]
**Is your feature request related to a problem? Please describe.**

The `flambe-output` folders take up a lot of space.

**Describe the solution you'd like**

An interactive `flambe clean` tool; upon invocation, it prints the locations of all `flambe-output` folders in a specified directory, their respective sizes, and a `Y/n` option to delete them en masse.

**Describe alternatives you've considered**

Writing a script to do this myself.

**Comment by williamabrwolf** [comment]
Alternatively/additionally, a flag that you can throw on the flambe running that deletes the output folder once the experiment ends.

**Comment by jeremyasapp** [comment]
At one point running Flambe with the `debug` flag did this, but I'm not sure if that's still the case. @iitzco-asapp

**Comment by jeremyasapp** [comment]
@williamabrwolf have you considered using the `-f` flag to keep overriding the flambe-output folder?

**Comment by williamabrwolf** [comment]
@jeremyasapp yeah, I use it (or else the experiment won't run); however, I'm running about 10 flambe experiments (looping over different trainsets, kinda thing), so 10 `flambe-output` folders stick around.

**Comment by williamabrwolf** [comment]
I think the best thing would be an option to delete folder once the experiment terminates?

**Comment by jeremyasapp** [comment]
Yeah makes sense. We'll add that in!

**Comment by williamabrwolf** [comment]
<3 #flambe

**Comment by jeremyasapp** [comment]
Option 1: require a safe path and have an extra flag `delete_output`
Option 2: save path is `flambe-output` by default, but specifying None will not save anything

**Comment by williamabrwolf** [comment]
Bump :)

**Comment by jeremyasapp** [comment]
Added a `--no-save` option in the 0.5 refactor! :)
