### ISSUE TITLE
Improve checks when launching processes using tmux

### ISSUE THREAD

**Issue by iitzco-asapp** [asappresearch/flambe#33]
`tmux` is currently used to launch the processes in the clusters (`flambe` and `flambe-site`)  and there are some occasions where the process returns a non-success exit code but the process is actually launched correctly.
There is a current fix that checks if the process is running (regardless the exit code), but this may not be the best solution for the problem.

**Comment by jeremyasapp** [comment]
This is irrelevant in v0.5.
