### ISSUE TITLE
Recurring ValueError when refreshing TensorBoard

### ISSUE THREAD

**Issue by williamabrwolf** [asappresearch/flambe#64]
I'm often seeing the following `ValueError`:

```
  File "/persist/git/flambe/flambe/experiment/progress.py", line 66, in refresh
    k, v = h.split('=')
ValueError: not enough values to unpack (expected 2, got 1)
```

This happens when viewing TensorBoard in browser, and refreshing the page; the above error is logged to console by the server. This doesn't break anything, but it seems like a bug all the same.

**Comment by jeremyasapp** [comment]
Are you doing : `!g` with a single value inside?

**Comment by iitzco-asapp** [comment]
@williamabrwolf I think jeremy could be right

> Are you doing : !g with a single value inside?

**Comment by jeremyasapp** [comment]
Closing for now.
