### ISSUE TITLE
Tokenize arrays of strings

### ISSUE THREAD

**Issue by williamabrwolf** [asappresearch/flambe#93]
**Is your feature request related to a problem? Please describe.**

The `BaseSampler` *will* handle *arrays of tensors* elegantly. However, these arrays only come to be if you manually construct them yourself.

**Describe the solution you'd like**

To be able to have an array-as-one-observation, and for the `TextField` to handle that gracefully (then pass it along to the `BaseSampler`).

**Additional context**

Models that embed a large sequence of context utterances, where simply joining those utterances into one string makes for one really long string.

**Comment by jeremyasapp** [comment]
Done in #255
